services:
  - type: web
    name: dklautomatie-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ADMIN_EMAIL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: APP_ENV
        value: prod
        sync: false
    healthCheckPath: /api/health
    buildCommand: docker build -t dklautomatie-backend .
    startCommand: docker run -p 8080:8080 dklautomatie-backend 